### ISSUE TITLE
location_address_* fields are null

### ISSUE THREAD

**Issue by neilberkman** [codersagainstcovidorg/covid19testing-backend#10]
A few days ago when I fetched data from the `/location` endpoint, the `location_address_locality`, `location_address_postal_code` and `location_address_region` fields were all populated. Now these seem to be `null` for every location and `location_address_street` contains the full address. Was this intentional? It's useful to have this data parsed out.

Example: 

```
    "location_address_locality": null,
    "location_address_postal_code": null,
    "location_address_region": null,
    "location_address_street": "6350 E Galbraith Rd, Cincinnati, OH 45236",
```

**Comment by jorge-caballero** [comment]
Hi @neilberkman - we're in the process of migrating our schema to align with that of our data partners. The only way we could do that without falling too far behind in terms of data ingestion was to *temporarily* split the difference w/r/t the address fields. It seems like you may have already taken a stab at parsing the addresses yourself, and can see why it was a bigger project than at first glance. Turns out that crowdsourced data is dirty...so we'll need to figure out exactly how to structure the data at the point of capture even though we don't have full control of the interface being used by our data partners. 

Open to suggestions!

**Comment by neilberkman** [comment]
Hi @jorge-caballero - Thanks for the response. I wasn't aware that this was an explicit decision on your part to make this change. I was hoping it was the result of an inadvertent regression on your end.

With data we've been getting from other sources we've been geocoding via Google's API. Most of the time we get a result and in the small number of cases where we don't we modify the address manually. Once we have the result from Google we reassemble the address in the form we need it (street / city / state / zip) based on the components in the result. We apply some logic to handle locations that are specified as intersections rather than street addressees, those with subpremeses, etc.

When we discovered your API one advantage was that you already had the address parsed out into the fields we needed, and you had lat & long as well. Given that the parsed out addresses is no longer available we'll just call the Geocoder API for your data as well.
